# GPT-4o generated
topics = [
    "User's favorite color and why",
    "The most memorable moment in User's life",
    "User's favorite season and activities",
    "The best concert User has ever attended",
    "User's dream job and career aspirations",
    "A country User wants to visit and why",
    "User's favorite childhood memory",
    "The most inspiring person in User's life",
    "User's go-to comfort food",
    "A skill User wants to learn",
    "User's favorite holiday and traditions",
    "The book that changed User's perspective",
    "User's favorite type of weather",
    "The most adventurous thing User has done",
    "User's favorite way to relax",
    "A project User is proud of",
    "The most difficult decision User has made",
    "User's favorite sport to watch",
    "A movie that User can watch repeatedly",
    "User's favorite genre of music",
    "The best gift User has ever received",
    "User's favorite place to hang out with friends",
    "The most valuable lesson User has learned",
    "User's favorite way to spend a weekend",
    "The kindest act User has experienced",
    "User's favorite type of cuisine",
    "A historical event User wishes they witnessed",
    "User's favorite hobby",
    "The place User feels most at peace",
    "User's biggest fear and how they cope with it",
    "The best piece of advice User has received",
    "User's favorite family tradition",
    "The accomplishment User is most proud of",
    "User's favorite way to exercise",
    "A dream User has yet to achieve",
    "User's favorite animal and why",
    "The best meal User has ever had",
    "User's morning routine",
    "A time when User felt most challenged",
    "User's favorite type of art",
    "The person User admires the most",
    "User's favorite place to travel",
    "The best lesson User has learned from a mistake",
    "User's favorite scent and why",
    "A hobby User would like to pick up",
    "The most influential teacher User had",
    "User's favorite way to give back to the community",
    "A time when User felt truly happy",
    "User's favorite season of the year",
    "The most creative thing User has done",
    "User's favorite TV show and why",
    "A personal goal User is working towards",
    "User's favorite outdoor activity",
    "The book User is currently reading",
    "User's favorite way to stay motivated",
    "A person User would like to have dinner with",
    "User's favorite way to celebrate a milestone",
    "A challenge User overcame",
    "User's favorite time of day",
    "A cause User is passionate about",
    "User's favorite place to shop",
    "A skill User is proud of",
    "User's favorite type of flower",
    "The best vacation User has had",
    "User's favorite type of dessert",
    "A subject User enjoyed in school",
    "User's favorite way to unwind after a long day",
    "A habit User wants to develop",
    "User's favorite childhood book",
    "The most surprising thing User has learned about themselves",
    "User's favorite way to stay healthy",
    "A movie that made a strong impact on User",
    "User's favorite indoor activity",
    "The best compliment User has received",
    "User's favorite kind of pet",
    "A place User would like to live someday",
    "User's favorite thing about their culture",
    "A talent User wishes they had",
    "User's favorite way to spend time with family",
    "A piece of technology User finds indispensable",
    "User's favorite way to express creativity",
    "The most fun User has had in the past year",
    "User's favorite motivational quote",
    "A challenge User is currently facing",
    "User's favorite type of clothing",
    "The most generous thing User has done",
    "User's favorite way to learn new things",
    "A historical figure User admires",
    "User's favorite way to relax on a rainy day",
    "A goal User has for the next year",
    "User's favorite part of their daily routine",
    "The most inspiring book User has read",
    "User's favorite type of movie",
    "A place User wants to revisit",
    "User's favorite way to stay organized",
    "The best surprise User has received",
    "User's favorite way to spend a day off",
    "A person who made a significant impact on User's life",
    "User's favorite way to celebrate holidays",
    "A quote that inspires User daily"
]
